/* imgheader.c -- https://github.com/takeiteasy/tools
 
 The MIT License (MIT)

 Copyright (c) 2022 George Watson

 Permission is hereby granted, free of charge, to any person
 obtaining a copy of this software and associated documentation
 files (the "Software"), to deal in the Software without restriction,
 including without limitation the rights to use, copy, modify, merge,
 publish, distribute, sublicense, and/or sell copies of the Software,
 and to permit persons to whom the Software is furnished to do so,
 subject to the following conditions:

 The above copyright notice and this permission notice shall be
 included in all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. */

#define STB_IMAGE_IMPLEMENTATION
#define STBI_NO_GIF
#include "stb_image.h"
#include <stdio.h>
#include <assert.h>
#include <string.h>
#if defined(_WIN32) || defined(_WIN64)
#include <io.h>
#define F_OK 0
#define access _access
#else
#include <unistd.h>
#endif

#define BAIL(X, MSG, ...)                                     \
    do {                                                      \
        if (!(X)) {                                           \
            fprintf(stderr, "ERROR: " MSG "\n", __VA_ARGS__); \
            usage();                                          \
        }                                                     \
        assert((X));                                          \
    } while(0)

static const char* FileExt(const char *path) {
    const char *dot = strrchr(path, '.');
    return !dot || dot == path ? NULL : dot + 1;
}

static const char* RemoveExt(const char* path) {
    char *lastExt = strrchr(path, '.');
    if (lastExt != NULL)
        *lastExt = '\0';
    return lastExt ? path : NULL;
}

static const char* FileName(const char *path) {
    int l = 0;
    char *tmp = strstr(path, "/");
    do {
        l = strlen(tmp) + 1;
        path = &path[strlen(path) - l + 2];
        tmp = strstr(path, "/");
    } while(tmp);
    return RemoveExt(path);
}

static const char *ValidExtensions[10] = {
    "jpg", "jpeg", "png", "bmp", "psd", "tga", "hdr", "pic", "ppm", "pgm"
};

static void usage(void) {
    printf("usage: imgheader <in> <out:optional>\n");
    printf("\tValid extensions:\n");
    for (int i = 0; i < 10; i++)
        printf("\t - %s\n", ValidExtensions[i]);
}

int main(int argc, const char *argv[]) {
    BAIL(argc == 2 || argc == 3, "Incorrect arguments: %d, expected 1 or 2", argc - 1);
    int ValidExt = 0;
    const char *ext = FileExt(argv[1]);
    int extLength = strlen(ext);
    for (int i = 0; i < 10; i++)
        if (!strncmp(ext, ValidExtensions[i], extLength)) {
            ValidExt = 1;
            break;
        }
    BAIL(ValidExt, "Invalid extension: %s", ext);
    BAIL(!access(argv[1], F_OK), "File doesn't exist at: \"%s\"", argv[1]);
    
    int w, h, n;
    unsigned char *data = stbi_load(argv[1], &w, &h, &n, 4);
    BAIL(data && w > 0 && h > 0, "Failed to load image at: \"%s\"", argv[1]);
    
    char outPath[512];
    char *outName = (char*)FileName(argv[1]);
    switch (argc) {
        case 2:
            outPath[0] = '\0';
            break;
        case 3: {
            int pathLength = strlen(argv[2]);
            memcpy(outPath, argv[2], sizeof(char) * pathLength);
            outPath[pathLength] = '\0';
            break;
        }
        default:
            usage();
            return 1;
    }
    for (int i = 0; i < strlen(outName); i++)
        if (outName[i] == '.')
            outName[i] = '_';
    
    FILE *out = outPath[0] == '\0' ? stdout : fopen(outPath, "w");
    fprintf(out, "// Generated by img2header.c -- https://github.com/takeiteasy/\n"
                 "\n"
                 "#ifndef __IMG__%s__H__\n"
                 "#define __IMG__%s__H__\n",
                 outName, outName);
    const int size = w * h * 4;
    fprintf(out, "static const unsigned char img_%s_data[%d] = {", outName, size);
    for (int i = 0, j = 0; i < size; i++, j++) {
        if (!j)
            printf("\n\t");
        fprintf(out, "%d%s", data[i], i == size - 1 ? ",\n};\n" : ", ");
        if (j == 2)
            j = -1;
    }
    fprintf(out, "static const int img_%s_data_sz = %d;\n", outName, size);
    fprintf(out, "static const int img_%s_width = %d;\n", outName, w);
    fprintf(out, "static const int img_%s_height = %d;\n", outName, h);
    fprintf(out, "#endif // __IMG__%s__H__\n", outName);
    
    free(data);
    if (outPath[0] != '\0')
        fclose(out);
    return 0;
}
